package cumulus.dotfiles.theme

import cumulus.dotfiles.context.Context
import cumulus.dotfiles.error.{CommandError, CumulusError}

object ThemeEngine:
  def run(ctx: Context, args: List[String]): Either[CumulusError, Unit] =
    if args.isEmpty then
      cumulus.dotfiles.pickers.WofiPickers.runThemePicker(ctx, args)
    else
      val flavor = args.head
      var mode = "wallpaper"
      var customWallpaper: Option[String] = None
      var interval = "30m"

      var i = 1
      while i < args.length do
        args(i) match
          case "--flat" =>
            mode = "flat"
            i += 1
          case "--wallpaper" if i + 1 < args.length =>
            mode = "wallpaper"
            customWallpaper = Some(args(i + 1))
            i += 2
          case "--rotate" =>
            mode = "rotate"
            if i + 1 < args.length && !args(i + 1).startsWith("-") then
              interval = args(i + 1)
              i += 2
            else
              i += 1
          case _ =>
            i += 1

      applyTheme(ctx, flavor, mode, customWallpaper, interval)

  def applyTheme(
      ctx: Context,
      flavor: String,
      mode: String = "wallpaper",
      customWallpaper: Option[String] = None,
      interval: String = "30m"
  ): Either[CumulusError, Unit] =
    println(s"\u001b[1;35m[cumulus theme]\u001b[0m Applying theme '$flavor' (mode: $mode)...")
    val palette = Palette.find(flavor, ctx)

    // Resolve wallpaper path
    val activeWallpaper = mode match
      case "flat" => ""
      case "rotate" => resolveWallpaperForFlavor(ctx, palette.name).getOrElse("")
      case _ => customWallpaper.getOrElse(resolveWallpaperForFlavor(ctx, palette.name).getOrElse(""))

    // 1. Write global state file ~/.config/cumulus/theme/state (read by Neovim and desktop apps)
    val stateDir = ctx.configDir / "cumulus" / "theme"
    os.makeDir.all(stateDir)
    val stateFile = stateDir / "state"
    val nvimColorscheme = s"${palette.name}-theme"
    val stateContent =
      s"""FLAVOR=${palette.name}
         |MODE=$mode
         |WALLPAPER=$activeWallpaper
         |WALLPAPER_SOURCE=${if mode == "rotate" then "rotate" else if mode == "flat" then "flat" else "single"}
         |INTERVAL=$interval
         |NVIM_COLORSCHEME=$nvimColorscheme
         |""".stripMargin
    os.write.over(stateFile, stateContent)
    println(s"  \u001b[32m[OK]\u001b[0m Global theme state written -> $stateFile")

    // 2. Render Sway colors.conf (~/.config/sway/colors.conf)
    val swayDir = ctx.configDir / "sway"
    os.makeDir.all(swayDir)
    val swayColorsFile = swayDir / "colors.conf"
    val wallpaperCmd = if activeWallpaper.nonEmpty then
      s"exec_always pkill -x swaybg; swaybg -i '$activeWallpaper' -m fill"
    else
      "exec_always pkill -x swaybg"

    val swayColorsContent =
      s"""# Generated by cumulus dotfiles theme engine — flavor=${palette.name} mode=$mode
         |$wallpaperCmd
         |
         |# class                 border      bg          text        indicator   child_border
         |client.focused          ${palette.accent}   ${palette.base}   ${palette.text}   ${palette.accent}   ${palette.accent}
         |client.focused_inactive ${palette.mantle}   ${palette.base}   ${palette.text}   ${palette.mantle}   ${palette.mantle}
         |client.unfocused        ${palette.mantle}   ${palette.base}   #9ca3af             ${palette.mantle}   ${palette.mantle}
         |client.urgent           ${palette.red}      ${palette.base}   ${palette.red}      ${palette.red}      ${palette.red}
         |""".stripMargin
    os.write.over(swayColorsFile, swayColorsContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Sway colors -> $swayColorsFile")

    // 3. Render Kitty theme.conf & colors.conf (~/.config/kitty/)
    val kittyDir = ctx.configDir / "kitty"
    os.makeDir.all(kittyDir)
    val kittyThemeFile = kittyDir / "theme.conf"
    val kittyColorsFile = kittyDir / "colors.conf"
    val kittyContent =
      s"""# Generated by cumulus.dotfiles theme engine
         |background ${palette.base}
         |foreground ${palette.text}
         |selection_background ${palette.accent}
         |cursor ${palette.accent}
         |""".stripMargin
    os.write.over(kittyThemeFile, kittyContent)
    os.write.over(kittyColorsFile, kittyContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Kitty theme -> $kittyThemeFile")

    // 4. Render Waybar theme CSS & style.css (~/.config/waybar/)
    val waybarDir = ctx.configDir / "waybar"
    os.makeDir.all(waybarDir)
    val waybarThemeFile = waybarDir / "theme.css"
    val waybarStyleFile = waybarDir / "style.css"
    val waybarContent =
      s"""/* Generated by cumulus.dotfiles theme engine */
         |@define-color base ${palette.base};
         |@define-color mantle ${palette.mantle};
         |@define-color text ${palette.text};
         |@define-color accent ${palette.accent};
         |@define-color red ${palette.red};
         |@define-color green ${palette.green};
         |@define-color yellow ${palette.yellow};
         |@define-color blue ${palette.blue};
         |""".stripMargin
    os.write.over(waybarThemeFile, waybarContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Waybar theme -> $waybarThemeFile")

    val waybarStyleContent =
      """@import "theme.css";
        |
        |* {
        |    font-family: "JetBrainsMono Nerd Font", sans-serif;
        |    font-size: 13px;
        |    min-height: 0;
        |    border: none;
        |    border-radius: 0;
        |    transition: none;
        |}
        |
        |window#waybar {
        |    background-color: @base;
        |    color: @text;
        |}
        |
        |#workspaces button {
        |    padding: 0 8px;
        |    background-color: transparent;
        |    color: @text;
        |}
        |
        |#workspaces button.focused {
        |    background-color: @mantle;
        |    color: @accent;
        |    border-bottom: 2px solid @accent;
        |}
        |
        |#workspaces button.urgent {
        |    background-color: @red;
        |    color: @base;
        |}
        |
        |#clock,
        |#tray,
        |#network,
        |#bluetooth,
        |#pulseaudio,
        |#backlight,
        |#battery,
        |#custom-notification,
        |#mode {
        |    padding: 0 10px;
        |    margin: 0 2px;
        |    color: @text;
        |}
        |
        |#battery.warning {
        |    color: @yellow;
        |}
        |
        |#battery.critical {
        |    color: @red;
        |}
        |
        |#network.disconnected {
        |    color: @red;
        |}
        |""".stripMargin
    os.write.over(waybarStyleFile, waybarStyleContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Waybar style -> $waybarStyleFile")

    // 5. Render Wofi theme CSS (~/.config/wofi/theme.css)
    val wofiDir = ctx.configDir / "wofi"
    os.makeDir.all(wofiDir)
    val wofiThemeFile = wofiDir / "theme.css"
    val wofiContent =
      s"""/* Generated by cumulus.dotfiles theme engine */
         |window { background-color: ${palette.base}; color: ${palette.text}; }
         |#entry:selected { background-color: ${palette.accent}; color: ${palette.base}; }
         |""".stripMargin
    os.write.over(wofiThemeFile, wofiContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Wofi theme -> $wofiThemeFile")

    // 6. Update active-theme symlink for compatibility
    val activeThemeSymlink = swayDir / "active-theme"
    try
      if os.exists(activeThemeSymlink) || os.isLink(activeThemeSymlink) then os.remove(activeThemeSymlink)
      os.write.over(activeThemeSymlink, s"THEME_NAME=${palette.name}\nACCENT_COLOR=${palette.accent}\n")
    catch
      case _: Exception => ()

    // 7. Apply wallpaper live via swaybg
    if activeWallpaper.nonEmpty then
      try
        os.proc("pkill", "-x", "swaybg").call(check = false)
        os.proc("swaybg", "-i", activeWallpaper, "-m", "fill").spawn()
        println(s"  \u001b[32m[OK]\u001b[0m Applied wallpaper -> $activeWallpaper")
      catch
        case _: Exception => ()
    else
      try os.proc("pkill", "-x", "swaybg").call(check = false) catch case _: Exception => ()

    // 8. Trigger live reloads across desktop applications
    cumulus.dotfiles.refresh.RefreshEngine.runRefresh(ctx)
    Right(())

  def resolveWallpaperForFlavor(ctx: Context, flavor: String): Option[String] =
    val wallpapersDir = ctx.dotfilesDir / "themes" / "wallpapers"
    if os.exists(wallpapersDir) then
      val candidates = Seq(
        wallpapersDir / s"${flavor}.svg",
        wallpapersDir / s"${flavor}_2.svg",
        wallpapersDir / s"${flavor}_3.svg",
        wallpapersDir / s"${flavor}.png",
        wallpapersDir / s"${flavor}.jpg"
      )
      candidates.find(os.exists).map(_.toString).orElse {
        os.list(wallpapersDir).find(f => f.ext == "svg" || f.ext == "png" || f.ext == "jpg").map(_.toString)
      }
    else None

  def listWallpapers(ctx: Context): Seq[String] =
    val wallpapersDir = ctx.dotfilesDir / "themes" / "wallpapers"
    if os.exists(wallpapersDir) then
      os.list(wallpapersDir)
        .filter(f => f.ext == "svg" || f.ext == "png" || f.ext == "jpg")
        .map(_.toString)
        .sorted
    else Nil
