package cumulus.dotfiles.theme

import cumulus.dotfiles.context.Context
import cumulus.dotfiles.error.{CommandError, CumulusError}

object ThemeEngine:
  def run(ctx: Context, args: List[String]): Either[CumulusError, Unit] =
    val flavor = args.headOption.getOrElse("catppuccin-mocha")
    val mode = args.lift(1).getOrElse("dark")

    println(s"\u001b[1;35m[cumulus theme]\u001b[0m Applying theme '$flavor' (mode: $mode)...")
    val palette = Palette.find(flavor)

    // Render Kitty theme config
    val kittyDir = ctx.configDir / "kitty"
    os.makeDir.all(kittyDir)
    val kittyThemeFile = kittyDir / "theme.conf"
    val kittyContent =
      s"""# Generated by cumulus.dotfiles theme engine
         |background ${palette.base}
         |foreground ${palette.text}
         |selection_background ${palette.accent}
         |cursor ${palette.accent}
         |""".stripMargin
    os.write.over(kittyThemeFile, kittyContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Kitty theme -> $kittyThemeFile")

    // Render Waybar theme CSS
    val waybarDir = ctx.configDir / "waybar"
    os.makeDir.all(waybarDir)
    val waybarThemeFile = waybarDir / "theme.css"
    val waybarContent =
      s"""/* Generated by cumulus.dotfiles theme engine */
         |@define-color base ${palette.base};
         |@define-color mantle ${palette.mantle};
         |@define-color text ${palette.text};
         |@define-color accent ${palette.accent};
         |""".stripMargin
    os.write.over(waybarThemeFile, waybarContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Waybar theme -> $waybarThemeFile")

    // Render Wofi theme CSS
    val wofiDir = ctx.configDir / "wofi"
    os.makeDir.all(wofiDir)
    val wofiThemeFile = wofiDir / "theme.css"
    val wofiContent =
      s"""/* Generated by cumulus.dotfiles theme engine */
         |window { background-color: ${palette.base}; color: ${palette.text}; }
         |#entry:selected { background-color: ${palette.accent}; color: ${palette.base}; }
         |""".stripMargin
    os.write.over(wofiThemeFile, wofiContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Wofi theme -> $wofiThemeFile")

    // Update active theme symlink
    val activeThemeSymlink = ctx.configDir / "sway" / "active-theme"
    try
      if os.exists(activeThemeSymlink) || os.isLink(activeThemeSymlink) then os.remove(activeThemeSymlink)
      os.write.over(activeThemeSymlink, s"THEME_NAME=${palette.name}\nACCENT_COLOR=${palette.accent}\n")
    catch
      case _: Exception => ()

    // Trigger live reloads across desktop applications
    cumulus.dotfiles.refresh.RefreshEngine.runRefresh(ctx)
    Right(())
