package cumulus.dotfiles.theme

import cumulus.dotfiles.context.Context
import cumulus.dotfiles.error.{CommandError, CumulusError}

object ThemeEngine:
  def run(ctx: Context, args: List[String]): Either[CumulusError, Unit] =
    if args.isEmpty then
      cumulus.dotfiles.pickers.WofiPickers.runThemePicker(ctx, args)
    else
      val flavor = args.head
      var mode = "wallpaper"
      var customWallpaper: Option[String] = None
      var interval = "30m"

      var i = 1
      while i < args.length do
        args(i) match
          case "--flat" =>
            mode = "flat"
            i += 1
          case "--wallpaper" if i + 1 < args.length =>
            mode = "wallpaper"
            customWallpaper = Some(args(i + 1))
            i += 2
          case "--rotate" =>
            mode = "rotate"
            if i + 1 < args.length && !args(i + 1).startsWith("-") then
              interval = args(i + 1)
              i += 2
            else
              i += 1
          case _ =>
            i += 1

      applyTheme(ctx, flavor, mode, customWallpaper, interval)

  def getActivePalette(ctx: Context): Palette =
    val stateFile = ctx.configDir / "cumulus" / "theme" / "state"
    if os.exists(stateFile) then
      val flavorOpt = os.read.lines(stateFile).find(_.startsWith("FLAVOR=")).map(_.stripPrefix("FLAVOR="))
      flavorOpt.map(f => Palette.find(f, ctx)).getOrElse(Palette.FallbackPalette)
    else
      Palette.find("aws", ctx)

  def applyTheme(
      ctx: Context,
      flavor: String,
      mode: String = "wallpaper",
      customWallpaper: Option[String] = None,
      interval: String = "30m"
  ): Either[CumulusError, Unit] =
    println(s"\u001b[1;35m[cumulus theme]\u001b[0m Applying theme '$flavor' (mode: $mode)...")
    val palette = Palette.find(flavor, ctx)

    // Resolve wallpaper path
    val activeWallpaper = mode match
      case "flat" => ""
      case "rotate" => resolveWallpaperForFlavor(ctx, palette.name).getOrElse("")
      case _ => customWallpaper.getOrElse(resolveWallpaperForFlavor(ctx, palette.name).getOrElse(""))

    // 1. Write global state file ~/.config/cumulus/theme/state (read by Neovim and desktop apps)
    val stateDir = ctx.configDir / "cumulus" / "theme"
    os.makeDir.all(stateDir)
    val stateFile = stateDir / "state"
    val nvimColorscheme = s"${palette.name}-theme"
    val stateContent =
      s"""FLAVOR=${palette.name}
         |MODE=$mode
         |WALLPAPER=$activeWallpaper
         |WALLPAPER_SOURCE=${if mode == "rotate" then "rotate" else if mode == "flat" then "flat" else "single"}
         |INTERVAL=$interval
         |NVIM_COLORSCHEME=$nvimColorscheme
         |""".stripMargin
    os.write.over(stateFile, stateContent)
    println(s"  \u001b[32m[OK]\u001b[0m Global theme state written -> $stateFile")

    // 2. Render Sway colors.conf (~/.config/sway/colors.conf)
    val swayDir = ctx.configDir / "sway"
    os.makeDir.all(swayDir)
    val swayColorsFile = swayDir / "colors.conf"
    val wallpaperDirective = if activeWallpaper.nonEmpty then
      s"output * bg \"$activeWallpaper\" fill"
    else
      "# No wallpaper"

    val swayColorsContent =
      s"""# Generated by cumulus dotfiles theme engine — flavor=${palette.name} mode=$mode
         |$wallpaperDirective
         |
         |# class                 border      bg          text        indicator   child_border
         |client.focused          ${palette.accent}   ${palette.base}   ${palette.text}   ${palette.accent}   ${palette.accent}
         |client.focused_inactive ${palette.mantle}   ${palette.base}   ${palette.text}   ${palette.mantle}   ${palette.mantle}
         |client.unfocused        ${palette.mantle}   ${palette.base}   #9ca3af             ${palette.mantle}   ${palette.mantle}
         |client.urgent           ${palette.red}      ${palette.base}   ${palette.red}      ${palette.red}      ${palette.red}
         |""".stripMargin
    os.write.over(swayColorsFile, swayColorsContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Sway colors -> $swayColorsFile")

    // 3. Render Kitty theme.conf & colors.conf (~/.config/kitty/)
    val kittyDir = ctx.configDir / "kitty"
    os.makeDir.all(kittyDir)
    val kittyThemeFile = kittyDir / "theme.conf"
    val kittyColorsFile = kittyDir / "colors.conf"
    val kittyContent =
      s"""# Generated by cumulus.dotfiles theme engine
         |background ${palette.base}
         |foreground ${palette.text}
         |selection_background ${palette.accent}
         |cursor ${palette.accent}
         |""".stripMargin
    os.write.over(kittyThemeFile, kittyContent)
    os.write.over(kittyColorsFile, kittyContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Kitty theme -> $kittyThemeFile")

    // 4. Render Waybar theme CSS & style.css (~/.config/waybar/)
    val waybarDir = ctx.configDir / "waybar"
    os.makeDir.all(waybarDir)
    val waybarThemeFile = waybarDir / "theme.css"
    val waybarStyleFile = waybarDir / "style.css"
    val waybarContent =
      s"""/* Generated by cumulus.dotfiles theme engine */
         |@define-color base ${palette.base};
         |@define-color mantle ${palette.mantle};
         |@define-color text ${palette.text};
         |@define-color accent ${palette.accent};
         |@define-color red ${palette.red};
         |@define-color green ${palette.green};
         |@define-color yellow ${palette.yellow};
         |@define-color blue ${palette.blue};
         |""".stripMargin
    os.write.over(waybarThemeFile, waybarContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Waybar theme -> $waybarThemeFile")

    val waybarStyleContent =
      """@import "theme.css";
        |
        |* {
        |    font-family: "JetBrainsMono Nerd Font", sans-serif;
        |    font-size: 13px;
        |    min-height: 0;
        |    border: none;
        |    border-radius: 0;
        |    transition: none;
        |}
        |
        |window#waybar {
        |    background-color: @base;
        |    color: @text;
        |}
        |
        |#workspaces button {
        |    padding: 0 8px;
        |    background-color: transparent;
        |    color: @text;
        |}
        |
        |#workspaces button.focused {
        |    background-color: @mantle;
        |    color: @accent;
        |    border-bottom: 2px solid @accent;
        |}
        |
        |#workspaces button.urgent {
        |    background-color: @red;
        |    color: @base;
        |}
        |
        |#clock,
        |#tray,
        |#network,
        |#bluetooth,
        |#pulseaudio,
        |#backlight,
        |#battery,
        |#custom-notification,
        |#mode {
        |    padding: 0 10px;
        |    margin: 0 2px;
        |    color: @text;
        |}
        |
        |#battery.warning {
        |    color: @yellow;
        |}
        |
        |#battery.critical {
        |    color: @red;
        |}
        |
        |#network.disconnected {
        |    color: @red;
        |}
        |
        |#custom-notification.notification {
        |    color: @accent;
        |}
        |
        |#custom-notification.dnd-notification,
        |#custom-notification.dnd-none,
        |#custom-notification.dnd-inhibited-notification,
        |#custom-notification.dnd-inhibited-none {
        |    opacity: 0.6;
        |}
        |""".stripMargin
    os.write.over(waybarStyleFile, waybarStyleContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Waybar style -> $waybarStyleFile")

    // 5. Render Wofi & Rofi launcher themes (~/.config/wofi/, ~/.config/rofi/)
    val wofiDir = ctx.configDir / "wofi"
    os.makeDir.all(wofiDir)
    val wofiThemeFile = wofiDir / "theme.css"
    val wofiStyleFile = wofiDir / "style.css"
    val wofiContent =
      s"""/* Generated by cumulus.dotfiles theme engine — flavor=${palette.name} */
         |window {
         |    background-color: ${palette.base};
         |    color: ${palette.text};
         |    border: 2px solid ${palette.accent};
         |    font-family: "JetBrainsMono Nerd Font";
         |    font-size: 14px;
         |}
         |#input {
         |    background-color: ${palette.mantle};
         |    color: ${palette.text};
         |    border: none;
         |    padding: 8px;
         |    margin: 8px;
         |}
         |#inner-box { background-color: ${palette.base}; }
         |#outer-box { padding: 4px; }
         |#scroll { margin: 4px; }
         |#entry { padding: 6px; }
         |#entry:selected {
         |    background-color: ${palette.accent};
         |    color: ${palette.base};
         |    border-radius: 4px;
         |}
         |#text { color: ${palette.text}; }
         |#text:selected { color: ${palette.base}; }
         |""".stripMargin
    os.write.over(wofiThemeFile, wofiContent)
    os.write.over(wofiStyleFile, wofiContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Wofi theme -> $wofiStyleFile")

    val rofiDir = ctx.configDir / "rofi"
    os.makeDir.all(rofiDir)
    val rofiThemeFile = rofiDir / "theme.rasi"
    val rofiConfigFile = rofiDir / "config.rasi"
    val rofiThemeContent =
      s"""/* Generated by cumulus.dotfiles theme engine — flavor=${palette.name} */
         |* {
         |    bg: ${palette.base};
         |    fg: ${palette.text};
         |    accent: ${palette.accent};
         |    mantle: ${palette.mantle};
         |    font: "JetBrainsMono Nerd Font 12";
         |    background-color: transparent;
         |    text-color: @fg;
         |}
         |window {
         |    background-color: @bg;
         |    text-color: @fg;
         |    border: 2px;
         |    border-color: @accent;
         |    border-radius: 8px;
         |    padding: 12px;
         |    width: 600px;
         |}
         |mainbox {
         |    children: [ inputbar, listview ];
         |}
         |inputbar {
         |    children: [ prompt, entry ];
         |    background-color: @mantle;
         |    border-radius: 6px;
         |    padding: 8px;
         |    margin: 0 0 12px 0;
         |}
         |prompt {
         |    background-color: @accent;
         |    text-color: @bg;
         |    padding: 4px 8px;
         |    border-radius: 4px;
         |}
         |entry {
         |    placeholder: "Search apps...";
         |    placeholder-color: #6c7086;
         |    padding: 4px 8px;
         |    text-color: @fg;
         |}
         |listview {
         |    lines: 8;
         |    columns: 1;
         |    fixed-height: false;
         |}
         |element {
         |    padding: 8px;
         |    border-radius: 6px;
         |}
         |element selected {
         |    background-color: @accent;
         |    text-color: @bg;
         |}
         |element-text {
         |    text-color: inherit;
         |}
         |element-icon {
         |    size: 24px;
         |    margin: 0 8px 0 0;
         |}
         |""".stripMargin
    val rofiConfigContent =
      s"""/* Generated by cumulus.dotfiles theme engine — flavor=${palette.name} */
        |configuration {
        |    modi: "drun,run,window";
        |    show-icons: true;
        |    icon-theme: "Papirus";
        |    terminal: "kitty";
        |    drun-display-format: "{icon} {name}";
        |}
        |@theme "${rofiThemeFile.toString}"
        |""".stripMargin
    os.write.over(rofiThemeFile, rofiThemeContent)
    os.write.over(rofiConfigFile, rofiConfigContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Rofi theme -> $rofiThemeFile")

    // 6. Render Swaylock config (~/.config/swaylock/config)
    val swaylockDir = ctx.configDir / "swaylock"
    os.makeDir.all(swaylockDir)
    val swaylockConfigFile = swaylockDir / "config"
    val baseHex = palette.base.stripPrefix("#")
    val mantleHex = palette.mantle.stripPrefix("#")
    val textHex = palette.text.stripPrefix("#")
    val accentHex = palette.accent.stripPrefix("#")
    val redHex = palette.red.stripPrefix("#")

    val imageSetting = if activeWallpaper.nonEmpty then s"image=$activeWallpaper\nscaling=fill" else s"color=$baseHex"

    val swaylockContent =
      s"""# Generated by cumulus dotfiles theme engine
         |$imageSetting
         |font=JetBrainsMono Nerd Font
         |font-size=26
         |indicator-radius=115
         |indicator-thickness=14
         |ring-color=$mantleHex
         |inside-color=${baseHex}CC
         |text-color=$textHex
         |key-hl-color=$accentHex
         |bs-hl-color=$redHex
         |line-color=$mantleHex
         |inside-ver-color=${accentHex}CC
         |ring-ver-color=$accentHex
         |inside-wrong-color=${redHex}CC
         |ring-wrong-color=$redHex
         |inside-clear-color=${baseHex}CC
         |ring-clear-color=$accentHex
         |text-clear-color=$textHex
         |text-ver-color=$textHex
         |text-wrong-color=$textHex
         |show-failed-attempts
         |""".stripMargin
    os.write.over(swaylockConfigFile, swaylockContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Swaylock config -> $swaylockConfigFile")

    // 7. Update active-theme symlink for compatibility
    val activeThemeSymlink = swayDir / "active-theme"
    try
      if os.exists(activeThemeSymlink) || os.isLink(activeThemeSymlink) then os.remove(activeThemeSymlink)
      os.write.over(activeThemeSymlink, s"THEME_NAME=${palette.name}\nACCENT_COLOR=${palette.accent}\n")
    catch
      case _: Exception => ()

    // 8. Apply wallpaper live via Sway output bg
    if activeWallpaper.nonEmpty then
      try
        os.proc("swaymsg", "output", "*", "bg", activeWallpaper, "fill").call(check = false)
        println(s"  \u001b[32m[OK]\u001b[0m Applied wallpaper via Sway -> $activeWallpaper")
      catch
        case _: Exception => ()

    // 8b. Render Mako notification daemon config (~/.config/mako/config)
    val makoDir = ctx.configDir / "mako"
    os.makeDir.all(makoDir)
    val makoFile = makoDir / "config"
    val makoContent =
      s"""# Mako notification daemon configuration
         |# Generated by cumulus.dotfiles theme engine — flavor=${palette.name}
         |
         |output=*
         |width=300
         |margin=10
         |padding=10
         |border-size=1
         |border-radius=5
         |background-color=${palette.base}
         |border-color=${palette.accent}
         |text-color=${palette.text}
         |font=Monospace 10
         |default-timeout=5000
         |""".stripMargin
    os.write.over(makoFile, makoContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered Mako config -> $makoFile")

    // 8c. Render SwayNC style stylesheet (~/.config/swaync/style.css)
    val swayncDir = ctx.configDir / "swaync"
    os.makeDir.all(swayncDir)
    val swayncFile = swayncDir / "style.css"
    val swayncContent =
      s"""/* Generated by cumulus.dotfiles theme engine — flavor=${palette.name} */
         |* {
         |    font-family: "JetBrainsMono Nerd Font", sans-serif;
         |    font-size: 13px;
         |}
         |
         |.control-center {
         |    background-color: ${palette.base};
         |    color: ${palette.text};
         |    border: 2px solid ${palette.accent};
         |    border-radius: 8px;
         |    padding: 14px;
         |}
         |
         |.control-center-list {
         |    background: transparent;
         |}
         |
         |.floating-notifications {
         |    background: transparent;
         |}
         |
         |.notification-row {
         |    outline: none;
         |    margin: 6px 0;
         |}
         |
         |.notification {
         |    background-color: ${palette.mantle};
         |    border: 1px solid ${palette.accent};
         |    border-radius: 6px;
         |    padding: 10px;
         |    color: ${palette.text};
         |}
         |
         |.notification-content {
         |    background: transparent;
         |    padding: 4px;
         |}
         |
         |.close-button {
         |    background: transparent;
         |    color: ${palette.text};
         |    border-radius: 4px;
         |    padding: 4px;
         |}
         |
         |.close-button:hover {
         |    background-color: ${palette.red};
         |    color: ${palette.base};
         |}
         |
         |.widget-title {
         |    color: ${palette.text};
         |    font-size: 15px;
         |    font-weight: bold;
         |    margin: 8px;
         |}
         |
         |.widget-title > button {
         |    background-color: ${palette.mantle};
         |    color: ${palette.text};
         |    border: 1px solid ${palette.accent};
         |    border-radius: 6px;
         |    padding: 4px 10px;
         |}
         |
         |.widget-title > button:hover {
         |    background-color: ${palette.accent};
         |    color: ${palette.base};
         |}
         |
         |.widget-dnd {
         |    background-color: ${palette.mantle};
         |    border: 1px solid ${palette.accent};
         |    border-radius: 6px;
         |    padding: 8px 12px;
         |    margin: 8px;
         |}
         |
         |.widget-dnd > switch {
         |    background-color: ${palette.base};
         |    border-radius: 12px;
         |    border: 1px solid ${palette.accent};
         |}
         |
         |.widget-dnd > switch:checked {
         |    background-color: ${palette.accent};
         |}
         |
         |.widget-mpris {
         |    background-color: ${palette.mantle};
         |    border: 1px solid ${palette.accent};
         |    border-radius: 6px;
         |    padding: 8px;
         |    margin: 8px;
         |}
         |
         |.widget-mpris-title {
         |    font-weight: bold;
         |    color: ${palette.text};
         |}
         |
         |.widget-mpris-subtitle {
         |    color: ${palette.text};
         |    opacity: 0.8;
         |}
         |""".stripMargin
    os.write.over(swayncFile, swayncContent)
    println(s"  \u001b[32m[OK]\u001b[0m Rendered SwayNC style -> $swayncFile")

    // 9. Trigger live reloads across desktop applications
    cumulus.dotfiles.refresh.RefreshEngine.runRefresh(ctx)
    Right(())

  def resolveWallpaperForFlavor(ctx: Context, flavor: String): Option[String] =
    val wallpapersDir = ctx.dotfilesDir / "themes" / "wallpapers"
    if os.exists(wallpapersDir) then
      val candidates = Seq(
        wallpapersDir / s"${flavor}.svg",
        wallpapersDir / s"${flavor}_2.svg",
        wallpapersDir / s"${flavor}_3.svg",
        wallpapersDir / s"${flavor}.png",
        wallpapersDir / s"${flavor}.jpg"
      )
      candidates.find(os.exists).map(_.toString).orElse {
        os.list(wallpapersDir).find(f => f.ext == "svg" || f.ext == "png" || f.ext == "jpg").map(_.toString)
      }
    else None

  def listWallpapers(ctx: Context): Seq[String] =
    val wallpapersDir = ctx.dotfilesDir / "themes" / "wallpapers"
    if os.exists(wallpapersDir) then
      os.list(wallpapersDir)
        .filter(f => f.ext == "svg" || f.ext == "png" || f.ext == "jpg")
        .map(_.toString)
        .sorted
    else Nil
