#!/usr/bin/env bash
#
# theme.sh — select a desktop flavor + background mode for this whole
# desktop (sway, waybar, wofi, kitty) and apply it live.
#
# Concepts:
#   - Flavor: one of the palettes in themes/palettes/*.sh, including the four
#       Catppuccin flavors and the AWS/Azure/GCP/OCI cloud themes.
#   - Background mode:
#       flat      — solid color using the flavor's "base" swatch (default,
#                   no wallpaper image at all).
#       wallpaper — a single static image from themes/wallpapers/.
#       rotate    — cycle through every image in themes/wallpapers/ on a
#                   timer (systemd --user timer), same flavor's colors used
#                   throughout regardless of which image is showing.
#
# State is persisted in ~/.config/cumulus/theme/state so it re-applies the
# same way after reboot/login (wired into sway's exec_always) and after
# ./install.sh (wired automatically).
#
# Usage:
#   ./theme.sh set <flavor>                              # flat color (default mode)
#   ./theme.sh set <flavor> --preserve-background        # keep current wallpaper/rotation mode
#   ./theme.sh set <flavor> --wallpaper <path|filename>  # static wallpaper
#   ./theme.sh set <flavor> --rotate [--interval 30m]    # rotate images in themes/wallpapers/
#   ./theme.sh set <flavor> --flat                       # force flat color mode
#   ./theme.sh apply                                     # re-apply the saved state (no changes)
#   ./theme.sh next                                      # advance to the next wallpaper now (rotate mode)
#   ./theme.sh list                                      # list available flavors + wallpapers
#   ./theme.sh current                                   # show the active flavor/mode
#
set -euo pipefail

SELF="$(readlink -f "${BASH_SOURCE[0]}")"
DOTFILES_DIR="$(cd "$(dirname "$SELF")/.." && pwd)"
PALETTES_DIR="$DOTFILES_DIR/themes/palettes"
WALLPAPERS_DIR="$DOTFILES_DIR/themes/wallpapers"
STATE_DIR="$HOME/.config/cumulus/theme"
STATE_FILE="$STATE_DIR/state"
SYSTEMD_USER_DIR="$HOME/.config/systemd/user"

log() { printf '\033[1;35m[theme]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[theme] error:\033[0m %s\n' "$*" >&2; exit 1; }

valid_flavors() { basename -s .sh -a "$PALETTES_DIR"/*.sh; }

is_valid_flavor() {
  local f="$1"
  [ -f "$PALETTES_DIR/$f.sh" ]
}

validate_palette() {
  local flavor="$1" var
  for var in BASE MANTLE CRUST TEXT SUBTEXT1 SUBTEXT0 SURFACE0 SURFACE1 \
             SURFACE2 OVERLAY0 BLUE LAVENDER SAPPHIRE SKY TEAL GREEN YELLOW \
             PEACH MAROON RED MAUVE PINK FLAMINGO ROSEWATER; do
    [ -n "${!var:-}" ] || die "palette '$flavor' is missing required variable: $var"
  done
}

# ── Generate colors.conf/colors.css for each app from a palette file ────────
generate_configs() {
  local flavor="$1" mode="$2" wallpaper="${3:-}"
  unset NVIM_COLORSCHEME
  # shellcheck disable=SC1090
  source "$PALETTES_DIR/$flavor.sh"
  validate_palette "$flavor"

  mkdir -p "$STATE_DIR"

  # sway: wallpaper exec + client colors
  {
    echo "# Generated by scripts/theme.sh — flavor=$flavor mode=$mode. Do not edit by hand."
    if [ "$mode" = "flat" ]; then
      echo "exec_always swaybg -c \"$BASE\""
    else
      echo "exec_always swaybg -i \"$wallpaper\" -m fill"
    fi
    echo
    echo "# class                 border      bg          text        indicator   child_border"
    echo "client.focused          $BLUE       $BASE       $TEXT       $BLUE       $BLUE"
    echo "client.focused_inactive $SURFACE1   $BASE       $TEXT       $SURFACE1   $SURFACE1"
    echo "client.unfocused        $SURFACE0   $BASE       $SUBTEXT0   $SURFACE0   $SURFACE0"
    echo "client.urgent           $RED        $BASE       $RED        $RED        $RED"
  } > "$DOTFILES_DIR/config/sway/colors.conf"

  # waybar: render style.css from style.css.tmpl (@@PLACEHOLDER@@ substitution).
  # Rendered directly rather than via GTK CSS @import, since @import in GTK
  # CSS resolves relative to the consuming app's process CWD, not the
  # including file's location — fragile depending on how sway launches it.
  sed \
    -e "s/@@BASE@@/$BASE/g" -e "s/@@TEXT@@/$TEXT/g" -e "s/@@SUBTEXT0@@/$SUBTEXT0/g" \
    -e "s/@@SURFACE0@@/$SURFACE0/g" -e "s/@@BLUE@@/$BLUE/g" -e "s/@@RED@@/$RED/g" \
    -e "s/@@YELLOW@@/$YELLOW/g" \
    "$DOTFILES_DIR/config/waybar/style.css.tmpl" > "$DOTFILES_DIR/config/waybar/style.css"

  # wofi: same template-rendering approach.
  sed \
    -e "s/@@BASE@@/$BASE/g" -e "s/@@TEXT@@/$TEXT/g" \
    -e "s/@@SURFACE0@@/$SURFACE0/g" -e "s/@@BLUE@@/$BLUE/g" \
    "$DOTFILES_DIR/config/wofi/style.css.tmpl" > "$DOTFILES_DIR/config/wofi/style.css"

  # kitty: native kitty.conf syntax
  {
    echo "# Generated by scripts/theme.sh — flavor=$flavor. Do not edit by hand."
    echo "foreground $TEXT"
    echo "background $BASE"
    echo "selection_foreground $BASE"
    echo "selection_background $ROSEWATER"
    echo "cursor $ROSEWATER"
    echo "cursor_text_color $BASE"
    echo "url_color $ROSEWATER"
    echo "active_border_color $LAVENDER"
    echo "inactive_border_color $OVERLAY0"
    echo "bell_border_color $YELLOW"
    echo "wayland_titlebar_color background"
    echo "active_tab_background $BASE"
    echo "active_tab_foreground $TEXT"
    echo "inactive_tab_background $MANTLE"
    echo "inactive_tab_foreground $SUBTEXT0"
    echo "tab_bar_background $CRUST"
    echo "color0 $SURFACE1"
    echo "color8 $SURFACE2"
    echo "color1 $RED"
    echo "color9 $RED"
    echo "color2 $GREEN"
    echo "color10 $GREEN"
    echo "color3 $YELLOW"
    echo "color11 $YELLOW"
    echo "color4 $BLUE"
    echo "color12 $BLUE"
    echo "color5 $PINK"
    echo "color13 $PINK"
    echo "color6 $TEAL"
    echo "color14 $TEAL"
    echo "color7 $SUBTEXT1"
    echo "color15 $SUBTEXT0"
  } > "$DOTFILES_DIR/config/kitty/colors.conf"
}

# ── Reload the running apps to pick up the new colors ───────────────────────
reload_apps() {
  if command -v swaymsg >/dev/null 2>&1 && swaymsg -t get_version >/dev/null 2>&1; then
    swaymsg reload >/dev/null 2>&1 || true
    log "Reloaded sway (wallpaper + client colors + waybar/wofi css re-read on next launch)."
  else
    log "sway not running — colors will apply on next login."
  fi
}

# ── systemd --user timer for rotate mode ────────────────────────────────────
write_rotate_units() {
  local interval="$1"
  mkdir -p "$SYSTEMD_USER_DIR"

  cat > "$SYSTEMD_USER_DIR/cumulus-wallpaper-rotate.service" <<EOF
[Unit]
Description=cumulus.dotfiles wallpaper rotation (single tick)

[Service]
Type=oneshot
ExecStart=$DOTFILES_DIR/scripts/theme.sh next
EOF

  cat > "$SYSTEMD_USER_DIR/cumulus-wallpaper-rotate.timer" <<EOF
[Unit]
Description=cumulus.dotfiles wallpaper rotation timer

[Timer]
OnBootSec=$interval
OnUnitActiveSec=$interval
Persistent=true

[Install]
WantedBy=timers.target
EOF

  systemctl --user daemon-reload
  systemctl --user enable --now cumulus-wallpaper-rotate.timer
  log "Enabled rotation timer: every $interval (systemctl --user status cumulus-wallpaper-rotate.timer)"
}

disable_rotate_units() {
  if systemctl --user list-unit-files 2>/dev/null | grep -q cumulus-wallpaper-rotate.timer; then
    systemctl --user disable --now cumulus-wallpaper-rotate.timer >/dev/null 2>&1 || true
    log "Disabled rotation timer."
  fi
}

# ── Subcommands ──────────────────────────────────────────────────────────────
cmd_set() {
  local flavor="${1:-}"; shift || true
  [ -n "$flavor" ] || die "usage: theme.sh set <flavor> [--wallpaper <path>|--rotate [--interval N]|--flat]"
  is_valid_flavor "$flavor" || die "unknown flavor '$flavor' — choices: $(valid_flavors | tr '\n' ' ')"

  local mode="flat" wallpaper="" interval="30m"
  local preserve_background=false mode_explicit=false
  while [ $# -gt 0 ]; do
    case "$1" in
      --wallpaper) mode="wallpaper"; mode_explicit=true; wallpaper="$2"; shift 2 ;;
      --rotate) mode="rotate"; mode_explicit=true; shift ;;
      --interval) interval="$2"; shift 2 ;;
      --flat) mode="flat"; mode_explicit=true; shift ;;
      --preserve-background) preserve_background=true; shift ;;
      *) die "unknown option: $1" ;;
    esac
  done

  if $preserve_background && ! $mode_explicit && [ -f "$STATE_FILE" ]; then
    # shellcheck disable=SC1090
    source "$STATE_FILE"
    mode="${MODE:-flat}"
    wallpaper="${WALLPAPER:-}"
    interval="${INTERVAL:-30m}"
  fi

  if [ "$mode" = "wallpaper" ]; then
    [ -n "$wallpaper" ] || die "--wallpaper requires a path"
    # Allow bare filenames relative to themes/wallpapers/
    if [ ! -f "$wallpaper" ] && [ -f "$WALLPAPERS_DIR/$wallpaper" ]; then
      wallpaper="$WALLPAPERS_DIR/$wallpaper"
    fi
    [ -f "$wallpaper" ] || die "wallpaper not found: $wallpaper (put images in themes/wallpapers/ or pass a full path)"
    wallpaper="$(cd "$(dirname "$wallpaper")" && pwd)/$(basename "$wallpaper")"
  fi

  if [ "$mode" = "rotate" ]; then
    shopt -s nullglob
    local images=("$WALLPAPERS_DIR"/*.{jpg,jpeg,png,webp})
    shopt -u nullglob
    [ "${#images[@]}" -gt 0 ] || die "no images found in $WALLPAPERS_DIR — add some first"
    wallpaper="${images[0]}"
  fi

  # Load and validate metadata before persisting shared state.
  unset NVIM_COLORSCHEME
  # shellcheck disable=SC1090
  source "$PALETTES_DIR/$flavor.sh"
  validate_palette "$flavor"

  mkdir -p "$STATE_DIR"
  {
    echo "FLAVOR=$flavor"
    echo "MODE=$mode"
    echo "WALLPAPER=${wallpaper:-}"
    echo "INTERVAL=$interval"
    echo "NVIM_COLORSCHEME=${NVIM_COLORSCHEME:-}"
  } > "$STATE_FILE"

  generate_configs "$flavor" "$mode" "$wallpaper"

  if [ "$mode" = "rotate" ]; then
    write_rotate_units "$interval"
  else
    disable_rotate_units
  fi

  reload_apps
  log "Theme set: $flavor / $mode${wallpaper:+ ($(basename "$wallpaper"))}"
}

cmd_apply() {
  [ -f "$STATE_FILE" ] || { log "No saved theme state — applying default (mocha / flat)."; cmd_set mocha; return; }
  # shellcheck disable=SC1090
  source "$STATE_FILE"
  generate_configs "$FLAVOR" "$MODE" "${WALLPAPER:-}"
  [ "$MODE" = "rotate" ] && write_rotate_units "${INTERVAL:-30m}"
  reload_apps
  log "Re-applied saved theme: $FLAVOR / $MODE"
}

cmd_next() {
  [ -f "$STATE_FILE" ] || die "no theme set yet — run 'theme.sh set <flavor> --rotate' first"
  # shellcheck disable=SC1090
  source "$STATE_FILE"
  [ "$MODE" = "rotate" ] || die "current mode is '$MODE', not rotate — nothing to advance"

  shopt -s nullglob
  local images=("$WALLPAPERS_DIR"/*.{jpg,jpeg,png,webp})
  shopt -u nullglob
  [ "${#images[@]}" -gt 0 ] || die "no images found in $WALLPAPERS_DIR"

  local current="$WALLPAPER" next_idx=0 i
  for i in "${!images[@]}"; do
    if [ "${images[$i]}" = "$current" ]; then
      next_idx=$(( (i + 1) % ${#images[@]} ))
      break
    fi
  done
  local next_wallpaper="${images[$next_idx]}"

  sed -i "s|^WALLPAPER=.*|WALLPAPER=$next_wallpaper|" "$STATE_FILE"
  generate_configs "$FLAVOR" "rotate" "$next_wallpaper"
  reload_apps
  log "Advanced wallpaper -> $(basename "$next_wallpaper")"
}

cmd_list() {
  echo "Flavors:"
  local f
  for f in $(valid_flavors); do
    # shellcheck disable=SC1090
    source "$PALETTES_DIR/$f.sh"
    printf '  %-10s %s\n' "$f" "$THEME_LABEL"
  done
  echo
  echo "Wallpapers ($WALLPAPERS_DIR):"
  shopt -s nullglob
  local images=("$WALLPAPERS_DIR"/*.{jpg,jpeg,png,webp})
  shopt -u nullglob
  if [ "${#images[@]}" -eq 0 ]; then
    echo "  (none — drop image files in themes/wallpapers/ to use --wallpaper/--rotate)"
  else
    printf '  %s\n' "${images[@]##*/}"
  fi
}

cmd_current() {
  if [ -f "$STATE_FILE" ]; then
    # shellcheck disable=SC1090
    source "$STATE_FILE"
    echo "Flavor:  $FLAVOR"
    echo "Mode:    $MODE"
    [ -n "${WALLPAPER:-}" ] && echo "Image:   $(basename "$WALLPAPER")"
    if [ "$MODE" = "rotate" ]; then
      echo "Interval: ${INTERVAL:-30m}"
    fi
  else
    echo "No theme set yet (default is mocha / flat)."
  fi
}

main() {
  local sub="${1:-}"; shift || true
  case "$sub" in
    set) cmd_set "$@" ;;
    apply) cmd_apply ;;
    next) cmd_next ;;
    list) cmd_list ;;
    current) cmd_current ;;
    -h|--help|"") grep '^#' "$0" | sed 's/^#//'; exit 0 ;;
    *) die "unknown subcommand '$sub' (set/apply/next/list/current)" ;;
  esac
}

main "$@"
