//! Rendering the per-app config files and publishing them atomically.

use crate::bail;
use crate::context::Context;
use crate::error::Result;
use crate::theme::palette::{self, Palette};
use crate::theme::wallpaper::sway_shell_arg;
use crate::util;
use std::fs;
use std::path::{Path, PathBuf};

/// The four rendered config files, keyed by destination.
struct Rendered {
    sway: String,
    waybar: String,
    wofi: String,
    kitty: String,
}

/// Load + validate the palette, render every config, and publish them
/// all-or-nothing. Returns the loaded palette (for its metadata).
pub fn generate_configs(
    ctx: &Context,
    flavor: &str,
    mode: &str,
    wallpaper: &str,
) -> Result<Palette> {
    let p = Palette::load(ctx, flavor);
    p.validate(flavor)?;
    palette::validate_templates(ctx)?;
    let rendered = render(ctx, &p, mode, wallpaper, flavor)?;
    publish(ctx, &rendered)?;
    Ok(p)
}

fn render(
    ctx: &Context,
    p: &Palette,
    mode: &str,
    wallpaper: &str,
    flavor: &str,
) -> Result<Rendered> {
    let c = |k: &str| p.get(k).to_string();

    // sway: wallpaper exec + client colours.
    let mut sway = format!(
        "# Generated by scripts/theme.sh — flavor={flavor} mode={mode}. Do not edit by hand.\n"
    );
    if mode == "flat" {
        sway.push_str(&format!(
            "exec_always pkill -x swaybg; swaybg -c \"{}\"\n",
            c("BASE")
        ));
    } else {
        sway.push_str(&format!(
            "exec_always pkill -x swaybg; swaybg -i {} -m fill\n",
            sway_shell_arg(wallpaper)?
        ));
    }
    sway.push('\n');
    sway.push_str(
        "# class                 border      bg          text        indicator   child_border\n",
    );
    sway.push_str(&format!(
        "client.focused          {b}       {base}       {t}       {b}       {b}\n",
        b = c("BLUE"),
        base = c("BASE"),
        t = c("TEXT")
    ));
    sway.push_str(&format!(
        "client.focused_inactive {s1}   {base}       {t}       {s1}   {s1}\n",
        s1 = c("SURFACE1"),
        base = c("BASE"),
        t = c("TEXT")
    ));
    sway.push_str(&format!(
        "client.unfocused        {s0}   {base}       {st0}   {s0}   {s0}\n",
        s0 = c("SURFACE0"),
        base = c("BASE"),
        st0 = c("SUBTEXT0")
    ));
    sway.push_str(&format!(
        "client.urgent           {r}        {base}       {r}        {r}        {r}\n",
        r = c("RED"),
        base = c("BASE")
    ));

    // waybar / wofi: @@PLACEHOLDER@@ substitution.
    let waybar = read_template(&ctx.config_src("waybar/style.css.tmpl"))?
        .replace("@@BASE@@", &c("BASE"))
        .replace("@@TEXT@@", &c("TEXT"))
        .replace("@@SUBTEXT0@@", &c("SUBTEXT0"))
        .replace("@@SURFACE0@@", &c("SURFACE0"))
        .replace("@@BLUE@@", &c("BLUE"))
        .replace("@@RED@@", &c("RED"))
        .replace("@@YELLOW@@", &c("YELLOW"));

    let wofi = read_template(&ctx.config_src("wofi/style.css.tmpl"))?
        .replace("@@BASE@@", &c("BASE"))
        .replace("@@TEXT@@", &c("TEXT"))
        .replace("@@SURFACE0@@", &c("SURFACE0"))
        .replace("@@BLUE@@", &c("BLUE"));

    // kitty: native config syntax.
    let kitty = format!(
        "# Generated by scripts/theme.sh — flavor={flavor}. Do not edit by hand.\n\
foreground {text}\nbackground {base}\nselection_foreground {base}\nselection_background {rose}\n\
cursor {rose}\ncursor_text_color {base}\nurl_color {rose}\nactive_border_color {lav}\n\
inactive_border_color {ov0}\nbell_border_color {yellow}\nwayland_titlebar_color background\n\
active_tab_background {base}\nactive_tab_foreground {text}\ninactive_tab_background {mantle}\n\
inactive_tab_foreground {st0}\ntab_bar_background {crust}\ncolor0 {s1}\ncolor8 {s2}\n\
color1 {red}\ncolor9 {red}\ncolor2 {green}\ncolor10 {green}\ncolor3 {yellow}\ncolor11 {yellow}\n\
color4 {blue}\ncolor12 {blue}\ncolor5 {pink}\ncolor13 {pink}\ncolor6 {teal}\ncolor14 {teal}\n\
color7 {st1}\ncolor15 {st0}\n",
        text = c("TEXT"),
        base = c("BASE"),
        rose = c("ROSEWATER"),
        lav = c("LAVENDER"),
        ov0 = c("OVERLAY0"),
        yellow = c("YELLOW"),
        mantle = c("MANTLE"),
        st0 = c("SUBTEXT0"),
        crust = c("CRUST"),
        s1 = c("SURFACE1"),
        s2 = c("SURFACE2"),
        red = c("RED"),
        green = c("GREEN"),
        blue = c("BLUE"),
        pink = c("PINK"),
        teal = c("TEAL"),
        st1 = c("SUBTEXT1"),
    );

    Ok(Rendered {
        sway,
        waybar,
        wofi,
        kitty,
    })
}

fn read_template(path: &Path) -> Result<String> {
    match fs::read_to_string(path) {
        Ok(c) => Ok(c),
        Err(_) => bail!("missing theme template: {}", path.display()),
    }
}

/// All-or-nothing swap: stage new files, back up existing destinations, move
/// new files into place, and restore the backups if anything fails.
fn publish(ctx: &Context, r: &Rendered) -> Result<()> {
    let destinations = [
        ("sway", ctx.config_src("sway/colors.conf"), &r.sway),
        ("waybar", ctx.config_src("waybar/style.css"), &r.waybar),
        ("wofi", ctx.config_src("wofi/style.css"), &r.wofi),
        ("kitty", ctx.config_src("kitty/colors.conf"), &r.kitty),
    ];

    fs::create_dir_all(ctx.state_dir())?;
    let render_dir = util::mktemp_dir(&ctx.state_dir(), "render.")?;
    let backup_dir = util::mktemp_dir(&ctx.state_dir(), "publish.")?;

    let result = (|| -> Result<()> {
        let mut staged: Vec<(PathBuf, &Path)> = Vec::new();
        for (name, dest, content) in &destinations {
            let staged_path = render_dir.join(name);
            fs::write(&staged_path, content)?;
            staged.push((staged_path, dest.as_path()));
        }
        for (name, dest, _) in &destinations {
            if dest.exists() || util::is_symlink(dest) {
                fs::rename(dest, backup_dir.join(name))?;
            }
        }
        for (staged_path, dest) in &staged {
            fs::rename(staged_path, dest)?;
        }
        Ok(())
    })();

    if result.is_err() {
        // Roll back to the pre-publish state.
        for (_, dest, _) in &destinations {
            let _ = fs::remove_file(dest);
        }
        for (name, dest, _) in &destinations {
            let backup = backup_dir.join(name);
            if backup.exists() {
                let _ = fs::rename(&backup, dest);
            }
        }
        let _ = fs::remove_dir_all(&backup_dir);
        let _ = fs::remove_dir_all(&render_dir);
        bail!("could not publish generated theme configuration; previous files restored");
    }

    let _ = fs::remove_dir_all(&backup_dir);
    let _ = fs::remove_dir_all(&render_dir);
    Ok(())
}
